### ISSUE TITLE
Educonnect ... does not connect agora06

### ISSUE THREAD

**Issue by vingerha** [bain3/pronotepy#150]
Hi, with the new year ... new stuff too 
The educonnect has a in-between step which apparently does not work in the generic_functions.

Visual/manual
1. https://cas.agora06.fr/login?selection=EDU&service=https://0061670h.index-education.net/pronote/eleve.html
this opens a page where one has to select parent/legal-rep OR child/level
2. https://educonnect.education.gouv.fr/idp/profile/SAML2/POST/SSO?execution=e1s1
when clicking on eleve one gets to the logon page
3. https://educonnect.education.gouv.fr/idp/profile/SAML2/POST/SSO?execution=e1s1

The error comes from the 2nd page so it seems, it tries to put in user/pwd and continue but firts a button needs to be clicked
```
{"timestamp":1662362876482,"status":405,"error":"Method Not Allowed","exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method 'POST' not supported","path":"/delegate/redirect/EDU"}
```
![image](https://user-images.githubusercontent.com/44190435/188406944-ee85cd59-1d4b-4a2c-9016-9da809669442.png)

**Comment by Bapt5** [comment]
We don't click on buttons because we only use requests so no interaction with the web page. I just fixed the problem, it was just that last year Agora didn't use Educonnect and now it use it.

**Comment by vingerha** [comment]
Noticed you changed the cas_agora06
I copied the ent folder ... same/similar issue
```
{"timestamp":1662440640381,"status":405,"error":"Method Not Allowed","exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method 'POST' not supported","path":"/delegate/redirect/EDU"}
/home/arjan/.local/lib/python3.10/site-packages/bs4/__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(

**Comment by vingerha** [comment]
Better but still not working. 
I am happy to share a discord session so we can do this online and not send back/forth all this data :)
I added some statements in generic_function (see attached) and its output
[generic_funcTEXT.txt](https://github.com/bain3/pronotepy/files/9498229/generic_funcTEXT.txt)
[output.txt](https://github.com/bain3/pronotepy/files/9498232/output.txt)
the final error:
```
Traceback (most recent call last):
  File "/mnt/3692670A6ACD9016/docker/homeassistant1/python_scripts/pronote_2022/pronote_florian_cas2.py", line 20, in <module>
    client = pronotepy.Client('https://0061670h.index-education.net/pronote/eleve.html', username, password, ent)
  File "/mnt/3692670A6ACD9016/docker/homeassistant1/python_scripts/pronote_2022/pronotepy/clients.py", line 382, in __init__
    super().__init__(pronote_url, username, password, ent, qr_code)
  File "/mnt/3692670A6ACD9016/docker/homeassistant1/python_scripts/pronote_2022/pronotepy/clients.py", line 81, in __init__
    self.attributes, self.func_options = self.communication.initialise()
  File "/mnt/3692670A6ACD9016/docker/homeassistant1/python_scripts/pronote_2022/pronotepy/pronoteAPI.py", line 77, in initialise
    self.attributes = self._parse_html(get_response.content)
  File "/mnt/3692670A6ACD9016/docker/homeassistant1/python_scripts/pronote_2022/pronotepy/pronoteAPI.py", line 274, in _parse_html
    raise PronoteAPIError(
pronotepy.exceptions.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.
```

**Comment by Bapt5** [comment]
I see the output and everything is going well. Maybe there is a problem with your pronote_url. But there is no problem with the ENT auth.

**Comment by vingerha** [comment]
Is there a way to share this without posting stuff on a publicly available website?

**Comment by Bapt5** [comment]
It has passed the selection parent/elev as evidenced by the logs you sent me. 
But I think there is a problem with the cookies but I can't solve it because I can't test anything because I don't have a login for your ENT

**Comment by vingerha** [comment]
again...can we do this separately ? I am ok to share but not via this page...  am 'vingerha' on discord

**Comment by vingerha** [comment]
vingerha#3240
